server:
  port: 8088

spring:
  redis:
    port: 6379
    username:
    password:
    host: 123.57.245.81
    lettuce:
      shutdown-timeout: 100 # 关闭超时时间
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        max-wait: 30  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0  # 连接池中的最小空闲连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: pc13320643636...
    url: jdbc:mysql://123.57.245.81:3306/wanxi_study_step2?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    hikari:
      connection-test-query: select 1
      connection-timeout: 60000
      idle-timeout: 500000
      minimum-idle: 10
      maximum-pool-size: 20
      connection-init-sql: select 1
      initialization-fail-timeout: 1

  application:
    name: rbacService
#  freemarker:
#    cache=false
#    charset=UTF-8
#    check-template-location=true
#    content-type=text/html
#    expose-request-attributes=true
#    expose-session-attributes=true
#    request-context-attribute=request
#    suffix=.ftl
jwt:
  #定义我们的盐  密码
  secret: white55open
  #过期时间
  expiration: 1800
  #token 的类型 说明他以 bearer 开头
  tokenHead: bearer
  #token 对应的 key
  tokenHeader: Authorization

esHost: 123.57.245.81
esPort: 9200


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.pc.rbac_system.model

#//开启sql日志打印
logging:
  level:
    com.pc.rbac_system.mapper: debug
